- name: prometheus on top docker
  hosts: appserver
  become: true
  tasks:
    - name: Pull the prometheus Docker image
      docker_image:
        name: bitnami/prometheus
        source: pull

    - name: copy prometheus.yml
      copy:
        src: /home/irwan/ansible/prometheus.yml
        dest: /home/irwansyah

    - name: Run the prometheus container
      docker_container:
        name: prometheus
        image: bitnami/prometheus
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9090:9090"
        volumes:
          - /home/irwansyah/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
